# Netlify deployment settings

[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm start"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  REACT_APP_API_URL = "Your API URL"